#! /usr/Python-2.7.9/python

import turtle
ventana=turtle.Screen()
ventana.bgcolor("orange")
ventana.title("Gerson Rulea")

vector=turtle.Vec2D(0,100)
g=turtle.Turtle()
g.setpos(vector)
print(g.pos())
ventana.exitonclick()
print ("Gerson Rulea l..l")

